---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: petclinic
spec:
  minReadySeconds: 3
  replicas: 3
  selector:
    matchLabels:
      app: petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: spring-petclinic
      labels:
        app: petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: abhish9416/petclinic:latest
          ports:
            - containerPort: 8080

